name: Issue Check

on:
  workflow_dispatch:
  issues:
    type: [opened]

jobs:
  issue_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: |
          if [ "${{ github.event.issue.title }}" == *"bug"* ]
          then
            curl -X POST  -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" -d '{"labels": ["bug"]}' ${{ github.event.issue.url }}/labels
          fi
